apiVersion: v1
kind: Service
metadata:
  name: holamundo
  labels:
    app: holamundo
  # namespace: default
spec:
  type: LoadBalancer
  selector:
    app: holamundo
  ports:
    - name: http
      port: 80
      targetPort: 8080
